### ISSUE TITLE
Is this still going?

### ISSUE THREAD

**Issue by Alexa-RR** [trueserve/openunifi#4]

**Comment by trueserve** [comment]
Nah, not really.

I've had way too many projects going on to work on this, and time has since passed and now there are products from UI that will mostly do what I need. I also tend to spend time maintaining networks rather than maintaining network equipment...

I may approach this at some time in the future as it should be relatively simple to implement (at least as far as access points and L2 switches go) but simply haven't had the time or motivation. Sorry.

**Comment by Alexa-RR** [comment]
okay thanks <3

**Comment by Bobu5** [comment]
Heyya there!, i really like the idea of this project, i have a TP-Link Deco M5 that had a pretty bad WebUI and are basically only managable from their app which had to connect to their chinese server first, yuck, i understand that you might not have the time and need to continue on this project as of right now but i really appreciate the effort you had put onto this project a few years back and would really love to participate and help if one day you or someone had decided to continue on working this project, Cheers!
